// <auto-generated />
using System;
using Assinaturas.Infrastructure.Persistence.Ef;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Assinaturas.Infrastructure.Persistence.Ef.Migrations
{
    [DbContext(typeof(AssinaturasDbContext))]
    [Migration("20231009041551_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.11");

            modelBuilder.Entity("Assinaturas.Domain.Assinaturas.Conta", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CreatedUserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar");

                    b.Property<byte[]>("Revision")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("BLOB");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UpdatedUserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id")
                        .HasName("PK_Contas_Id");

                    b.HasIndex(new[] { "Nome" }, "IX_Contas_Nome")
                        .IsUnique();

                    b.ToTable("Conta");
                });
#pragma warning restore 612, 618
        }
    }
}
