name: Pipeline da aplicação

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout do código
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x

    - name: Build da aplicação
      run: dotnet build --configuration Release

  test:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout do código
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x

    - name: Executa os testes
      run: dotnet test

  publish:
    needs: test
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout do código
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x

    - name: Publicação do artefato
      run: dotnet publish --configuration Release --output ./publish

    - name: Arquivação do artefato
      uses: actions/upload-artifact@v3
      with:
        name: webapi-artifact
        path: ./publish

  push_to_registry:
    needs: test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v3

    - name: Autenticação no Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Construção e publicação da imagem
      uses: docker/build-push-action@v4
      with:
        context: ./src/Assinaturas.WebApi
        push: true
        tags: |
          cristianomartinsdiasspbr1982/cast-validacao-conhecimentos:v${{ github.run_id }}
          cristianomartinsdiasspbr1982/cast-validacao-conhecimentos:latest
